### PR TITLE
ZNM rework tier 1-2

### PR DESCRIPTION
**Pull request by HaxPrime**
Removed all custom code from the tier one znm, these now match with upstream lsb. Tier 2 greatly reduced the mods but, I did leave resistances high to sleep, bind, gravity, silence and, lullaby. This is to make people fight the monsters as intended and not cheese through them.

### CODE REVIEW

**Comment by GravesXI** [comment]
get rid of the tabs lol

**Comment by HaxPrime** [comment]
okay, per Graves * going to raise the resistances to 10,000 on the tier 2's for bind, sleep, gravity, lullaby

**Comment by GravesXI** [comment]
looks better

**Comment by CatsEyeXI** [comment]
Is this ready for merge?

**Pull request merged**
