### PR TITLE
Dyinyanga NM

### PR DESCRIPTION
**Pull request by MowFord**
For tracking remaining items

### CODE REVIEW

**Comment by Spicyryan** [comment]
> For tracking remaining items

Just needs the silence and amnesia aura for anyone 0.5 yalms away, and to back off the target to regular melee distance when slow is on.

Not sure the distance specified is correct, but it should be literally on top of the player's position.

**Comment by MowFord** [comment]
> > For tracking remaining items
> 
> Just needs the silence and amnesia aura for anyone 0.5 yalms away, and to back off the target to regular melee distance when slow is on.
> 
> Not sure the distance specified is correct, but it should be literally on top of the player's position.

Distance specified is 5.0 yalms closer than normal...i.e he'll get as close as possible lol. We'll just set that mob mod based on having slow

**Comment by MowFord** [comment]
https://github.com/LandSandBoat/server/pull/5510/commits

Making a new branch for the lua, will close this when that's PR'd

**Comment by MowFord** [comment]
https://github.com/LandSandBoat/server/pull/5512

**Pull request closed without merging**
